app:
  container_name: app
  image: golang:1.5.2-alpine
  environment:
    - GO15VENDOREXPERIMENT=1
    - GIN_MODE=debug
    - HTTP_ADDR=:80
    - MONGO_ADDR=mongo:27017
    - MONGO_DB=wxmp
  volumes:
    - $GOPATH:/go
  working_dir: /go/src/github.com/Jackong/mphub
  command: "ash -c '\
  echo \"hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4\" >>/etc/nsswitch.conf \
  && go install . && mphub'"
  links:
    - mongo
mongo:
  container_name: mongo
  image: mongo:3.2.1
  volumes:
    - /data/mongo:/data/db
  command: "--storageEngine wiredTiger"
